/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.freewind.android.debugbridge.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param accepted 
 * @param message 
 * @param errorType 
 * @param timedOut 
 * @param durationMs 
 */
@JsonClass(generateAdapter = true)

data class ActionErrorResponse (

    @Json(name = "accepted")
    val accepted: kotlin.Boolean,

    @Json(name = "message")
    val message: kotlin.String,

    @Json(name = "errorType")
    val errorType: kotlin.String? = null,

    @Json(name = "timedOut")
    val timedOut: kotlin.Boolean? = null,

    @Json(name = "durationMs")
    val durationMs: kotlin.Int? = null

) {


}

