/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.freewind.android.debugbridge.api.models

import com.freewind.android.debugbridge.api.models.ActionRequest

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param name 
 * @param args 
 * @param summary 
 * @param example 
 */
@JsonClass(generateAdapter = true)

data class ActionCatalogItemAction (

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "args")
    val args: kotlin.collections.List<kotlin.String>,

    @Json(name = "summary")
    val summary: kotlin.String,

    @Json(name = "example")
    val example: ActionRequest

) {


}

