/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.freewind.android.debugbridge.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param accepted 
 * @param message 
 * @param action 
 * @param targetId 
 * @param durationMs 
 */
@JsonClass(generateAdapter = true)

data class ActionSuccessResponse (

    @Json(name = "accepted")
    val accepted: kotlin.Boolean,

    @Json(name = "message")
    val message: kotlin.String,

    @Json(name = "action")
    val action: kotlin.String? = null,

    @Json(name = "targetId")
    val targetId: kotlin.String? = null,

    @Json(name = "durationMs")
    val durationMs: kotlin.Int? = null

) {


}

