/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.freewind.android.debugbridge.api.models

import com.freewind.android.debugbridge.api.models.ActionCatalogItemAction

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param targetId 
 * @param targetType 
 * @param screen 
 * @param actions 
 */
@JsonClass(generateAdapter = true)

data class ActionCatalogItem (

    @Json(name = "targetId")
    val targetId: kotlin.String,

    @Json(name = "targetType")
    val targetType: kotlin.String,

    @Json(name = "screen")
    val screen: kotlin.String,

    @Json(name = "actions")
    val actions: kotlin.collections.List<ActionCatalogItemAction>

) {


}

