/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.freewind.android.debugbridge.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param action 
 * @param targetId 
 * @param text 
 * @param dx 
 * @param dy 
 * @param args 
 * @param source 
 */
@JsonClass(generateAdapter = true)

data class ActionRequest (

    @Json(name = "action")
    val action: kotlin.String,

    @Json(name = "targetId")
    val targetId: kotlin.String,

    @Json(name = "text")
    val text: kotlin.String? = null,

    @Json(name = "dx")
    val dx: kotlin.Int? = null,

    @Json(name = "dy")
    val dy: kotlin.Int? = null,

    @Json(name = "args")
    val args: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,

    @Json(name = "source")
    val source: kotlin.String? = null

) {


}

