/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.freewind.android.debugbridge.api.models

import com.freewind.android.debugbridge.api.models.ActionCatalogItem
import com.freewind.android.debugbridge.api.models.ActionCatalogSummary

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param summary 
 * @param items 
 */
@JsonClass(generateAdapter = true)

data class ActionCatalogResponse (

    @Json(name = "summary")
    val summary: ActionCatalogSummary,

    @Json(name = "items")
    val items: kotlin.collections.List<ActionCatalogItem>

) {


}

