/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.freewind.android.debugbridge.api.models

import com.freewind.android.debugbridge.api.models.HelpCounts
import com.freewind.android.debugbridge.api.models.HelpEndpoint

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param appName 
 * @param screenName 
 * @param serverTime 
 * @param capabilities 
 * @param counts 
 * @param endpoints 
 * @param examples 
 * @param consoleTitle 
 */
@JsonClass(generateAdapter = true)

data class HelpResponse (

    @Json(name = "appName")
    val appName: kotlin.String,

    @Json(name = "screenName")
    val screenName: kotlin.String,

    @Json(name = "serverTime")
    val serverTime: kotlin.String,

    @Json(name = "capabilities")
    val capabilities: kotlin.collections.List<kotlin.String>,

    @Json(name = "counts")
    val counts: HelpCounts,

    @Json(name = "endpoints")
    val endpoints: kotlin.collections.List<HelpEndpoint>,

    @Json(name = "examples")
    val examples: kotlin.collections.List<kotlin.String>,

    @Json(name = "consoleTitle")
    val consoleTitle: kotlin.String? = null

) {


}

