/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.freewind.android.debugbridge.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param actionTargetCount 
 * @param logCount 
 * @param stateKeyCount 
 * @param snapshotNodeCount 
 */
@JsonClass(generateAdapter = true)

data class HelpCounts (

    @Json(name = "actionTargetCount")
    val actionTargetCount: kotlin.Int,

    @Json(name = "logCount")
    val logCount: kotlin.Int,

    @Json(name = "stateKeyCount")
    val stateKeyCount: kotlin.Int,

    @Json(name = "snapshotNodeCount")
    val snapshotNodeCount: kotlin.Int

) {


}

