/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.freewind.android.debugbridge.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param method 
 * @param path 
 * @param summary 
 * @param queryFields 
 * @param bodyFields 
 */
@JsonClass(generateAdapter = true)

data class HelpEndpoint (

    @Json(name = "method")
    val method: kotlin.String,

    @Json(name = "path")
    val path: kotlin.String,

    @Json(name = "summary")
    val summary: kotlin.String,

    @Json(name = "queryFields")
    val queryFields: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "bodyFields")
    val bodyFields: kotlin.collections.List<kotlin.String>? = null

) {


}

