/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.freewind.android.debugbridge.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param seq 
 * @param time 
 * @param source 
 * @param level 
 * @param event 
 * @param summary 
 * @param `data` 
 * @param targetId 
 */
@JsonClass(generateAdapter = true)

data class LogEntry (

    @Json(name = "seq")
    val seq: kotlin.Int,

    @Json(name = "time")
    val time: kotlin.String,

    @Json(name = "source")
    val source: kotlin.String,

    @Json(name = "level")
    val level: kotlin.String,

    @Json(name = "event")
    val event: kotlin.String,

    @Json(name = "summary")
    val summary: kotlin.String,

    @Json(name = "data")
    val `data`: kotlin.collections.Map<kotlin.String, kotlin.String>,

    @Json(name = "targetId")
    val targetId: kotlin.String? = null

) {


}

