/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.freewind.android.debugbridge.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param accepted 
 * @param message 
 * @param clearedCount 
 */
@JsonClass(generateAdapter = true)

data class LogsClearResponse (

    @Json(name = "accepted")
    val accepted: kotlin.Boolean,

    @Json(name = "message")
    val message: kotlin.String,

    @Json(name = "clearedCount")
    val clearedCount: kotlin.Int

) {


}

