/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.freewind.android.debugbridge.api.models

import com.freewind.android.debugbridge.api.models.LogsTimeRange

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param total 
 * @param levelCounts 
 * @param sourceCounts 
 * @param eventCountsTop 
 * @param timeRange 
 */
@JsonClass(generateAdapter = true)

data class LogsSummary (

    @Json(name = "total")
    val total: kotlin.Int,

    @Json(name = "levelCounts")
    val levelCounts: kotlin.collections.Map<kotlin.String, kotlin.String>,

    @Json(name = "sourceCounts")
    val sourceCounts: kotlin.collections.Map<kotlin.String, kotlin.String>,

    @Json(name = "eventCountsTop")
    val eventCountsTop: kotlin.collections.Map<kotlin.String, kotlin.String>,

    @Json(name = "timeRange")
    val timeRange: LogsTimeRange? = null

) {


}

