/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.freewind.android.debugbridge.api.models

import com.freewind.android.debugbridge.api.models.SnapshotNode
import com.freewind.android.debugbridge.api.models.SnapshotSummary

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param summary 
 * @param fieldCatalog 
 * @param examples 
 * @param screen 
 * @param nodes 
 */
@JsonClass(generateAdapter = true)

data class SnapshotResponse (

    @Json(name = "summary")
    val summary: SnapshotSummary? = null,

    @Json(name = "fieldCatalog")
    val fieldCatalog: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "examples")
    val examples: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "screen")
    val screen: kotlin.String? = null,

    @Json(name = "nodes")
    val nodes: kotlin.collections.List<SnapshotNode>? = null

) {


}

