/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.freewind.android.debugbridge.api.models

import com.freewind.android.debugbridge.api.models.SnapshotBounds

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param parentId 
 * @param type 
 * @param text 
 * @param role 
 * @param backgroundColor 
 * @param contentColor 
 * @param visible 
 * @param enabled 
 * @param clickable 
 * @param `value` 
 * @param extra 
 * @param bounds 
 */
@JsonClass(generateAdapter = true)

data class SnapshotNode (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "parentId")
    val parentId: kotlin.String? = null,

    @Json(name = "type")
    val type: kotlin.String? = null,

    @Json(name = "text")
    val text: kotlin.String? = null,

    @Json(name = "role")
    val role: kotlin.String? = null,

    @Json(name = "backgroundColor")
    val backgroundColor: kotlin.String? = null,

    @Json(name = "contentColor")
    val contentColor: kotlin.String? = null,

    @Json(name = "visible")
    val visible: kotlin.Boolean? = null,

    @Json(name = "enabled")
    val enabled: kotlin.Boolean? = null,

    @Json(name = "clickable")
    val clickable: kotlin.Boolean? = null,

    @Json(name = "value")
    val `value`: kotlin.String? = null,

    @Json(name = "extra")
    val extra: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,

    @Json(name = "bounds")
    val bounds: SnapshotBounds? = null

) {


}

