/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.freewind.android.debugbridge.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param left 
 * @param top 
 * @param width 
 * @param height 
 */
@JsonClass(generateAdapter = true)

data class SnapshotBounds (

    @Json(name = "left")
    val left: kotlin.Double,

    @Json(name = "top")
    val top: kotlin.Double,

    @Json(name = "width")
    val width: kotlin.Double,

    @Json(name = "height")
    val height: kotlin.Double

) {


}

