/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.freewind.android.debugbridge.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param screen 
 * @param nodeCount 
 * @param rootIds 
 * @param typeCounts 
 * @param clickableCount 
 */
@JsonClass(generateAdapter = true)

data class SnapshotSummary (

    @Json(name = "screen")
    val screen: kotlin.String,

    @Json(name = "nodeCount")
    val nodeCount: kotlin.Int,

    @Json(name = "rootIds")
    val rootIds: kotlin.collections.List<kotlin.String>,

    @Json(name = "typeCounts")
    val typeCounts: kotlin.collections.Map<kotlin.String, kotlin.String>,

    @Json(name = "clickableCount")
    val clickableCount: kotlin.Int

) {


}

