/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.freewind.android.debugbridge.api.models

import com.freewind.android.debugbridge.api.models.StateKeySample

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param appStateKeys 
 * @param targetStateTargets 
 */
@JsonClass(generateAdapter = true)

data class StateSummary (

    @Json(name = "appStateKeys")
    val appStateKeys: kotlin.collections.List<StateKeySample>,

    @Json(name = "targetStateTargets")
    val targetStateTargets: kotlin.collections.List<kotlin.String>

) {


}

