/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.freewind.android.debugbridge.api.models

import com.freewind.android.debugbridge.api.models.StateSummary

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param summary 
 * @param appState 
 * @param targetState 
 */
@JsonClass(generateAdapter = true)

data class StateResponse (

    @Json(name = "summary")
    val summary: StateSummary? = null,

    @Json(name = "appState")
    val appState: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,

    @Json(name = "targetState")
    val targetState: kotlin.collections.Map<kotlin.String, kotlin.String>? = null

) {


}

